// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'age': string;
  'blur': string;
  'careerEnd': string;
  'careerStart': string;
  'cell': string;
  'checkInput': string;
  'country': string;
  'ethnicity': string;
  'externalLinks': string;
  'fullName': string;
  'gender': string;
  'hairColor': string;
  'monitored': string;
  'placeholder': string;
  'qualityProfileId': string;
  'rootFolderPath': string;
  'sizeOnDisk': string;
  'status': string;
  'statusIcon': string;
  'tags': string;
  'totalMovieCount': string;
  'totalSceneCount': string;
  'unmonitored': string;
}
export const cssExports: CssExports;
export default cssExports;
