// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButtons': string;
  'buttons': string;
  'footer': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
