// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'freeSpace': string;
  'importFiles': string;
  'importFormat': string;
  'link': string;
  'pathCell': string;
}
export const cssExports: CssExports;
export default cssExports;
