blank_issues_enabled: false
contact_links:
  - name: Support via Discord
    url: https://whisparr.com/discord
    about: Chat with users and devs on support and setup related topics.
  - name: Whisparr v2 (pink) issues
    url: https://github.com/Whisparr/Whisparr/issues
    about: Go here is you want to open an issue for Whisparr version 2.x (pink color scheme)
