// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'actionMenuIcon': string;
  'actionsMenu': string;
  'actionsMenuContent': string;
  'collapseButtonContainer': string;
  'expandButton': string;
  'expandButtonIcon': string;
  'footer': string;
  'header': string;
  'headerCenter': string;
  'headerRight': string;
  'hearerLeft': string;
  'monitorToggleButton': string;
  'movieCountTooltip': string;
  'noEpisodes': string;
  'refreshButton': string;
  'searchButton': string;
  'sizeOnDisk': string;
  'year': string;
  'yearNumber': string;
}
export const cssExports: CssExports;
export default cssExports;
