// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'info': string;
  'link': string;
  'overlayTitle': string;
  'poster': string;
  'posterContainer': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
