// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'aliases': string;
  'blur': string;
  'cell': string;
  'checkInput': string;
  'externalLinks': string;
  'network': string;
  'placeholder': string;
  'qualityProfileId': string;
  'rootFolderPath': string;
  'select': string;
  'sizeOnDisk': string;
  'sortTitle': string;
  'status': string;
  'statusIcon': string;
  'tags': string;
  'totalMovieCount': string;
  'totalSceneCount': string;
  'unmonitored': string;
}
export const cssExports: CssExports;
export default cssExports;
