// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'container': string;
  'content': string;
  'controls': string;
  'editorSelect': string;
  'ended': string;
  'externalLinks': string;
  'link': string;
  'monitorToggleButton': string;
  'nextAiring': string;
  'overlayTitle': string;
  'poster': string;
  'posterContainer': string;
  'progressBarOverlay': string;
  'qualityProfile': string;
  'sizeOnDisk': string;
  'studioLogo': string;
  'title': string;
  'totalMovieCount': string;
  'totalSceneCount': string;
}
export const cssExports: CssExports;
export default cssExports;
