#!/usr/bin/env node
// Renders the upstream sync backlog from .github/upstream/state.json.
//
// The state file is the only writable source of truth. UPSTREAM_SYNC.md and the
// upstream-watch tracking issues are both rendered from here, through this one
// code path, so they cannot drift apart.
//
//   --report   regenerate UPSTREAM_SYNC.md
//   --issue    print the tracking issue body for --upstream <name>
//   --check    exit non-zero if the report is stale, a disposition lacks a
//              reason, or en.json is not sorted case-insensitively

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const STATE = join(ROOT, '.github/upstream/state.json');
const REPORT = join(ROOT, 'UPSTREAM_SYNC.md');
const EN_JSON = join(ROOT, 'src/NzbDrone.Core/Localization/Core/en.json');

const GENERATED = '<!-- Generated by scripts/upstream-sync.mjs. Do not edit by hand. -->';

function fail(msg) {
  console.error(`error: ${msg}`);
  process.exitCode = 1;
}

async function gh(path) {
  const token = process.env.GITHUB_TOKEN ?? process.env.GH_TOKEN;
  const headers = { accept: 'application/vnd.github+json' };
  if (token) {
    headers.authorization = `Bearer ${token}`;
  }

  const res = await fetch(`https://api.github.com${path}`, { headers });
  if (!res.ok) {
    throw new Error(`GET ${path} -> ${res.status} ${res.statusText}`);
  }

  return res.json();
}

// Which tree a commit touches, using the same rule the skew report used.
function area(files) {
  const kinds = new Set(
    files.map((f) =>
      f.filename.startsWith('frontend/') ? 'fe' : f.filename.startsWith('src/') ? 'be' : 'other'
    )
  );

  if (kinds.has('be') && kinds.has('fe')) {
    return 'be+fe';
  }

  if (kinds.has('be')) {
    return 'be';
  }

  if (kinds.has('fe')) {
    return 'fe';
  }

  return 'chore';
}

// Commits on `branch` after the stored high-water mark that have no disposition
// recorded yet. Anything already picked, adapted, skipped or held is settled.
async function backlog(name, upstream, dispositions) {
  const { repo, branch, highWater } = upstream;
  const cmp = await gh(`/repos/${repo}/compare/${highWater}...${branch}`);

  const settled = dispositions[name] ?? {};
  const out = [];

  for (const c of cmp.commits) {
    if (settled[c.sha]) {
      continue;
    }

    const full = await gh(`/repos/${repo}/commits/${c.sha}`);

    out.push({
      sha: c.sha,
      date: c.commit.committer.date,
      subject: c.commit.message.split('\n')[0],
      author: c.commit.author?.name ?? 'unknown',
      area: area(full.files ?? []),
    });
  }

  out.sort((a, b) => a.date.localeCompare(b.date));
  return out;
}

function byMonth(commits) {
  const months = new Map();

  for (const c of commits) {
    const m = c.date.slice(0, 7);
    if (!months.has(m)) {
      months.set(m, []);
    }

    months.get(m).push(c);
  }

  return [...months.entries()].sort(([a], [b]) => a.localeCompare(b));
}

function renderUpstream(name, upstream, commits) {
  const lines = [];
  const label = `${upstream.repo} \`${upstream.branch}\``;

  lines.push(`## ${name} — ${label}`);
  lines.push('');
  lines.push(`Owns: **${upstream.owns}**. High-water mark: \`${upstream.highWater.slice(0, 10)}\`.`);
  lines.push('');

  if (commits.length === 0) {
    lines.push('Caught up — nothing outstanding.');
    lines.push('');
    return lines.join('\n');
  }

  lines.push(`**${commits.length} outstanding.**`);
  lines.push('');
  lines.push('| Month | Total | be | fe | be+fe | chore |');
  lines.push('| --- | ---: | ---: | ---: | ---: | ---: |');

  for (const [month, cs] of byMonth(commits)) {
    const n = (a) => cs.filter((c) => c.area === a).length;
    lines.push(
      `| ${month} | ${cs.length} | ${n('be')} | ${n('fe')} | ${n('be+fe')} | ${n('chore')} |`
    );
  }

  lines.push('');

  for (const [month, cs] of byMonth(commits)) {
    lines.push(`### ${month}`);
    lines.push('');

    for (const c of cs) {
      const url = `https://github.com/${upstream.repo}/commit/${c.sha}`;
      lines.push(
        `- \`${c.area.padEnd(5)}\` [\`${c.sha.slice(0, 9)}\`](${url}) ${c.subject} — *${c.author}*`
      );
    }

    lines.push('');
  }

  return lines.join('\n');
}

function renderSettled(state) {
  const lines = ['## Settled', '', 'Commits reviewed and dispositioned. Skips carry their reason.', ''];

  for (const [name, upstream] of Object.entries(state.upstreams)) {
    const settled = state.dispositions[name] ?? {};
    const entries = Object.entries(settled);

    if (entries.length === 0) {
      continue;
    }

    lines.push(`### ${name}`);
    lines.push('');
    lines.push('| Commit | Subject | Disposition | Reason |');
    lines.push('| --- | --- | --- | --- |');

    entries.sort(([, a], [, b]) => (a.month ?? '').localeCompare(b.month ?? ''));

    for (const [sha, d] of entries) {
      const url = `https://github.com/${upstream.repo}/commit/${sha}`;
      lines.push(
        `| [\`${sha.slice(0, 9)}\`](${url}) | ${d.subject} | \`${d.disposition}\` | ${d.reason} |`
      );
    }

    lines.push('');
  }

  return lines.join('\n');
}

async function render(state) {
  const parts = [
    GENERATED,
    '',
    '# Upstream sync',
    '',
    'We track two upstreams on two clocks: **frontend follows Sonarr, backend follows Radarr**.',
    'See `.github/upstream/state.json` for the machine state and the `sync-upstream` skill for the process.',
    '',
  ];

  for (const [name, upstream] of Object.entries(state.upstreams)) {
    const commits = await backlog(name, upstream, state.dispositions);
    parts.push(renderUpstream(name, upstream, commits), '');
  }

  parts.push(renderSettled(state));
  return parts.join('\n').replace(/\n{3,}/g, '\n\n');
}

// Our en.json is sorted case-insensitively; upstream's is not. Taking an
// upstream hunk wholesale is what breaks it, so guard the invariant here.
function checkEnJson() {
  const keys = Object.keys(JSON.parse(readFileSync(EN_JSON, 'utf8')));
  const bad = [];

  for (let i = 1; i < keys.length; i++) {
    if (keys[i - 1].toLowerCase() > keys[i].toLowerCase()) {
      bad.push(`${keys[i - 1]} before ${keys[i]}`);
    }
  }

  return bad;
}

function checkDispositions(state) {
  const valid = new Set(['pick', 'adapt', 'skip', 'have']);
  const problems = [];

  for (const [name, settled] of Object.entries(state.dispositions)) {
    for (const [sha, d] of Object.entries(settled)) {
      const at = `${name}/${sha.slice(0, 9)}`;

      if (!valid.has(d.disposition)) {
        problems.push(`${at}: unknown disposition "${d.disposition}"`);
      }

      if (!d.reason || d.reason.trim().length < 10) {
        problems.push(`${at}: needs a real reason`);
      }

      if (!d.subject) {
        problems.push(`${at}: missing subject`);
      }
    }
  }

  return problems;
}

const args = process.argv.slice(2);
const mode = args.find((a) => a.startsWith('--')) ?? '--report';
const state = JSON.parse(readFileSync(STATE, 'utf8'));

if (mode === '--check') {
  for (const p of checkDispositions(state)) {
    fail(p);
  }

  const enBad = checkEnJson();
  if (enBad.length > 0) {
    // One pre-existing violation is tracked separately; anything more is new.
    if (enBad.length > 1) {
      fail(`en.json is not sorted case-insensitively:\n  ${enBad.join('\n  ')}`);
    } else {
      console.warn(`warning: known en.json ordering issue: ${enBad[0]}`);
    }
  }

  let current = '';
  try {
    current = readFileSync(REPORT, 'utf8');
  } catch {
    fail('UPSTREAM_SYNC.md is missing — run with --report');
  }

  if (current && current !== (await render(state))) {
    fail('UPSTREAM_SYNC.md is stale — run with --report and commit the result');
  }

  if (process.exitCode) {
    console.error('\nupstream-sync --check failed');
  } else {
    console.log('upstream-sync --check passed');
  }
} else if (mode === '--issue') {
  const name = args[args.indexOf('--upstream') + 1];
  const upstream = state.upstreams[name];

  if (!upstream) {
    fail(`unknown upstream "${name}" — expected one of ${Object.keys(state.upstreams).join(', ')}`);
    process.exit(1);
  }

  const commits = await backlog(name, upstream, state.dispositions);
  console.log(renderUpstream(name, upstream, commits));
} else {
  writeFileSync(REPORT, await render(state));
  console.log(`wrote ${REPORT}`);
}
