#!/usr/bin/env node
// Renders the upstream sync backlog from .github/upstream/state.json.
//
// The state file is the only writable source of truth. UPSTREAM_SYNC.md and the
// upstream-watch tracking issues are both rendered from here, through this one
// code path, so they cannot drift apart.
//
//   --report   regenerate UPSTREAM_SYNC.md
//   --issue    print the tracking issue body for --upstream <name>
//   --check    exit non-zero if the report is stale, a disposition lacks a
//              reason, or en.json is not sorted case-insensitively
//   --attempt  cherry-pick the ungated part of one upstream's backlog onto a
//              branch and write the PR and issue bodies for it

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const STATE = join(ROOT, '.github/upstream/state.json');
const REPORT = join(ROOT, 'UPSTREAM_SYNC.md');
const EN_JSON = join(ROOT, 'src/NzbDrone.Core/Localization/Core/en.json');

const GENERATED = '<!-- Generated by scripts/upstream-sync.mjs. Do not edit by hand. -->';

// --report pins the upstream tips it rendered against and --check re-renders
// against those same tips. Without the pin, --check would compare a committed
// report against a moving branch, so every upstream push would turn CI red on
// every open PR - a check nobody could act on and everybody would learn to
// ignore.
const HEADS_RE = /^<!-- upstream-heads: (.*) -->$/m;

function fail(msg) {
  console.error(`error: ${msg}`);
  process.exitCode = 1;
}

async function gh(path) {
  const token = process.env.GITHUB_TOKEN ?? process.env.GH_TOKEN;
  const headers = { accept: 'application/vnd.github+json' };
  if (token) {
    headers.authorization = `Bearer ${token}`;
  }

  const res = await fetch(`https://api.github.com${path}`, { headers });
  if (!res.ok) {
    throw new Error(`GET ${path} -> ${res.status} ${res.statusText}`);
  }

  return res.json();
}

// GitHub caps /compare at 250 commits per response and reports the true
// figure in `total_commits`, so reading `commits` from a single call silently
// truncates any window wider than that - which is exactly how ten months of
// Sonarr stayed invisible. Walk every page and assert the count, so a future
// cap fails loudly instead of rendering a short list as a complete one.
async function compare(repo, base, head) {
  const commits = [];
  let total = 0;

  for (let page = 1; ; page += 1) {
    const cmp = await gh(`/repos/${repo}/compare/${base}...${head}?per_page=100&page=${page}`);

    total = cmp.total_commits;
    commits.push(...cmp.commits);

    if (cmp.commits.length === 0 || commits.length >= total) {
      break;
    }
  }

  if (commits.length !== total) {
    throw new Error(
      `compare ${repo} ${base}...${head} returned ${commits.length} of ${total} commits`
    );
  }

  return commits;
}

// Which tree a commit touches, using the same rule the skew report used.
function area(files) {
  const kinds = new Set(
    files.map((f) =>
      f.filename.startsWith('frontend/') ? 'fe' : f.filename.startsWith('src/') ? 'be' : 'other'
    )
  );

  if (kinds.has('be') && kinds.has('fe')) {
    return 'be+fe';
  }

  if (kinds.has('be')) {
    return 'be';
  }

  if (kinds.has('fe')) {
    return 'fe';
  }

  return 'chore';
}

// Commits on `branch` after the stored high-water mark that have no disposition
// recorded yet. Anything already picked, adapted, skipped or held is settled.
async function backlog(name, upstream, dispositions, ref) {
  const { repo, branch, highWater } = upstream;
  const commits = await compare(repo, highWater, ref ?? branch);

  const settled = dispositions[name] ?? {};
  const out = [];

  for (const c of commits) {
    if (settled[c.sha]) {
      continue;
    }

    const full = await gh(`/repos/${repo}/commits/${c.sha}`);

    out.push({
      sha: c.sha,
      date: c.commit.committer.date,
      subject: c.commit.message.split('\n')[0],
      author: c.commit.author?.name ?? 'unknown',
      area: area(full.files ?? []),
      files: (full.files ?? []).map((f) => f.filename),
      parents: c.parents?.length ?? 1,
    });
  }

  out.sort((a, b) => a.date.localeCompare(b.date));
  return out;
}

function byMonth(commits) {
  const months = new Map();

  for (const c of commits) {
    const m = c.date.slice(0, 7);
    if (!months.has(m)) {
      months.set(m, []);
    }

    months.get(m).push(c);
  }

  return [...months.entries()].sort(([a], [b]) => a.localeCompare(b));
}

function renderUpstream(name, upstream, commits, { detailMonths = Infinity } = {}) {
  const lines = [];
  const label = `${upstream.repo} \`${upstream.branch}\``;

  lines.push(`## ${name} — ${label}`);
  lines.push('');
  // Machine-readable so the watcher can tell an empty backlog from a full one
  // without parsing prose. Invisible once rendered.
  lines.push(`<!-- outstanding: ${commits.length} -->`);
  lines.push('');
  lines.push(`Owns: **${upstream.owns}**. High-water mark: \`${upstream.highWater.slice(0, 10)}\`.`);
  lines.push('');

  if (commits.length === 0) {
    lines.push('Caught up — nothing outstanding.');
    lines.push('');
    return lines.join('\n');
  }

  lines.push(`**${commits.length} outstanding.**`);
  lines.push('');
  lines.push('| Month | Total | be | fe | be+fe | chore |');
  lines.push('| --- | ---: | ---: | ---: | ---: | ---: |');

  for (const [month, cs] of byMonth(commits)) {
    const n = (a) => cs.filter((c) => c.area === a).length;
    lines.push(
      `| ${month} | ${cs.length} | ${n('be')} | ${n('fe')} | ${n('be+fe')} | ${n('chore')} |`
    );
  }

  lines.push('');

  byMonth(commits).forEach(([month, cs], i) => {
    lines.push(`### ${month}`);
    lines.push('');

    // Past the detail budget the month is summarised, not listed. The table
    // above still carries its counts, and UPSTREAM_SYNC.md still carries every
    // commit, so nothing is lost - it just does not have to fit in one issue.
    if (i >= detailMonths) {
      lines.push(`${cs.length} outstanding. Listed in \`UPSTREAM_SYNC.md\`; work the oldest month first.`);
      lines.push('');
      return;
    }

    for (const c of cs) {
      const url = `https://github.com/${upstream.repo}/commit/${c.sha}`;
      lines.push(
        `- \`${c.area.padEnd(5)}\` [\`${c.sha.slice(0, 9)}\`](${url}) ${c.subject} — *${c.author}*`
      );
    }

    lines.push('');
  });

  return lines.join('\n');
}

function renderSettled(state) {
  const lines = ['## Settled', '', 'Commits reviewed and dispositioned. Skips carry their reason.', ''];

  for (const [name, upstream] of Object.entries(state.upstreams)) {
    const settled = state.dispositions[name] ?? {};
    const entries = Object.entries(settled);

    if (entries.length === 0) {
      continue;
    }

    lines.push(`### ${name}`);
    lines.push('');
    lines.push('| Commit | Subject | Disposition | Reason |');
    lines.push('| --- | --- | --- | --- |');

    entries.sort(([, a], [, b]) => (a.month ?? '').localeCompare(b.month ?? ''));

    for (const [sha, d] of entries) {
      const url = `https://github.com/${upstream.repo}/commit/${sha}`;
      lines.push(
        `| [\`${sha.slice(0, 9)}\`](${url}) | ${d.subject} | \`${d.disposition}\` | ${d.reason} |`
      );
    }

    lines.push('');
  }

  return lines.join('\n');
}

async function branchHead(upstream) {
  const ref = await gh(`/repos/${upstream.repo}/git/ref/heads/${upstream.branch}`);
  return ref.object.sha;
}

// `heads` pins each upstream to the tip it is rendered against, so the same
// state file and the same tips always produce byte-identical output.
async function render(state, heads) {
  const parts = [
    GENERATED,
    `<!-- upstream-heads: ${Object.entries(heads)
      .map(([n, sha]) => `${n}=${sha}`)
      .join(' ')} -->`,
    '',
    '# Upstream sync',
    '',
    'We track two upstreams on two clocks: **frontend follows Sonarr, backend follows Radarr**.',
    'See `.github/upstream/state.json` for the machine state and the `sync-upstream` skill for the process.',
    '',
    `Backlogs below are as of ${Object.entries(heads)
      .map(([n, sha]) => `${n} \`${sha.slice(0, 10)}\``)
      .join(', ')}. Run \`--report\` to refresh; the tracking issues are the live view.`,
    '',
  ];

  for (const [name, upstream] of Object.entries(state.upstreams)) {
    const commits = await backlog(name, upstream, state.dispositions, heads[name]);
    parts.push(renderUpstream(name, upstream, commits), '');
  }

  parts.push(renderSettled(state));
  return parts.join('\n').replace(/\n{3,}/g, '\n\n');
}

function parseHeads(report) {
  const m = report.match(HEADS_RE);
  if (!m) {
    return null;
  }

  return Object.fromEntries(m[1].trim().split(/\s+/).map((pair) => pair.split('=')));
}

// The three standing gates from the sync-upstream skill, in the subset a
// machine can decide. Passing these is NOT a decision to take a commit - it
// only means nothing automatic is known to be wrong with it, so it is safe to
// put in front of a human as an applied diff rather than as a link.
function gateFor(name, commit) {
  // A merge has no single diff to replay, and `git cherry-pick` refuses one
  // without -m. Its constituent commits are listed separately by the compare
  // API anyway, so there is nothing here that is not covered elsewhere.
  if (commit.parents > 1) {
    return {
      gate: 'merge',
      reason: 'Merge commit. The commits it brings in are listed individually.',
    };
  }

  if (/translations updated by weblate/i.test(commit.subject)) {
    return {
      gate: 'weblate',
      reason: 'Translations come from Weblate, never from cherry-picks.',
    };
  }

  if (commit.files.some((f) => f.startsWith('src/NzbDrone.Core/Parser/'))) {
    return {
      gate: 'parser',
      reason:
        'Touches the parser. Our grammar parses scenes with dates, performers and studios; ' +
        'upstream regexes are tuned to a grammar we do not share. Needs a failing test against ' +
        'our parser first.',
    };
  }

  if (commit.files.includes('src/NzbDrone.Core/Localization/Core/en.json')) {
    return {
      gate: 'localization',
      reason:
        'Touches en.json. Ours is sorted case-insensitively and dozens of shared keys have ' +
        'different text here, so the upstream hunk has to be replaced by a key we author.',
    };
  }

  if (name === 'radarr' && commit.files.some((f) => f.startsWith('frontend/'))) {
    return {
      gate: 'radarr-frontend',
      reason:
        'Radarr frontend. Ours follows Sonarr, which finished the react-query conversion ' +
        'Radarr is still mid-way through.',
    };
  }

  return null;
}

function git(args, opts = {}) {
  return execFileSync('git', args, { cwd: ROOT, encoding: 'utf8', ...opts }).trim();
}

// Cherry-picks the ungated commits one at a time so a single conflict costs
// only that commit. Anything that conflicts is reported rather than resolved:
// guessing at a conflict resolution is exactly the judgement this must not make.
async function attempt(name, upstream, state) {
  const commits = await backlog(name, upstream, state.dispositions);
  const branch = `upstream-auto/${name}`;
  const trailerRepo = upstream.repo.toLowerCase();

  const gated = [];
  const candidates = [];

  for (const c of commits) {
    const g = gateFor(name, c);
    if (g) {
      gated.push({ ...c, ...g });
    } else {
      candidates.push(c);
    }
  }

  const applied = [];
  const conflicted = [];

  if (candidates.length > 0) {
    git(['fetch', '--filter=blob:none', '--no-tags', `https://github.com/${upstream.repo}.git`, upstream.branch]);
    git(['switch', '-C', branch]);

    for (const c of candidates) {
      try {
        git(['cherry-pick', '--no-rerere-autoupdate', c.sha], { stdio: 'pipe' });
      } catch {
        // The abort itself can fail - git refuses one when the pick never got
        // far enough to start - and that must not mask the pick failure.
        try {
          git(['cherry-pick', '--abort'], { stdio: 'pipe' });
        } catch {
          git(['reset', '--hard', 'HEAD'], { stdio: 'pipe' });
        }

        conflicted.push(c);
        continue;
      }

      const message = git(['log', '-1', '--pretty=%B']);
      git([
        'commit',
        '--amend',
        '-m',
        `${message}\n\n(cherry picked from commit ${trailerRepo}@${c.sha})`,
      ]);

      applied.push(c);
    }
  }

  return { name, upstream, branch, commits, gated, candidates, applied, conflicted };
}

function renderAttempt(result) {
  const { name, upstream, applied, gated, conflicted } = result;
  const lines = [];

  lines.push(
    `Opened by \`upstream-watch\` from ${upstream.repo} \`${upstream.branch}\`. **Draft on purpose.**`,
    ''
  );
  lines.push(
    'These commits applied cleanly and cleared the automatable gates. That is not a decision to',
    'take them: every one still needs the classify step from the `sync-upstream` skill, and',
    '`.github/upstream/state.json` has deliberately **not** been updated, so nothing here is',
    'recorded as settled yet.',
    ''
  );

  lines.push(`#### Applied (${applied.length})`, '');
  for (const c of applied) {
    lines.push(`- \`${c.area.padEnd(5)}\` [\`${c.sha.slice(0, 9)}\`](https://github.com/${upstream.repo}/commit/${c.sha}) ${c.subject}`);
  }
  lines.push('');

  if (conflicted.length > 0 || gated.length > 0) {
    lines.push(
      `Left out and tracked on the \`Upstream sync: ${upstream.repo.split('/')[1]} ${upstream.branch}\` issue`,
      'on Whisparr/Whisparr, where issues for both repos live:',
      `${conflicted.length} conflicted, ${gated.length} gated.`,
      ''
    );
  }

  lines.push('#### Database Migration', '', 'NO — but check each commit; the watcher cannot tell.', '');
  lines.push('#### Todos', '', '- [ ] Tests', '- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)', '');

  return lines.join('\n');
}

// GitHub rejects an issue body over 65536 characters. A backlog this wide
// blows past that on the commit list alone, and the workflow prepends a few
// lines of its own, so compose against a budget and spell out only the month
// actually being worked.
const ISSUE_BUDGET = 60000;

function renderIssue(name, upstream, commits, leftovers = '') {
  const body = [renderUpstream(name, upstream, commits, { detailMonths: 1 }), '', leftovers]
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trimEnd();

  if (body.length <= ISSUE_BUDGET) {
    return body;
  }

  const note =
    '\n\n> Truncated to fit one issue body. `UPSTREAM_SYNC.md` carries the full backlog.';
  const kept = body.slice(0, ISSUE_BUDGET - note.length);

  return kept.slice(0, kept.lastIndexOf('\n')) + note;
}

function renderLeftovers(result) {
  const { upstream, gated, conflicted } = result;
  const lines = [];

  if (conflicted.length > 0) {
    lines.push(`### Conflicted (${conflicted.length})`, '');
    lines.push('Did not apply on top of `eros-develop`. Needs porting by hand.', '');

    for (const c of conflicted) {
      lines.push(`- \`${c.area.padEnd(5)}\` [\`${c.sha.slice(0, 9)}\`](https://github.com/${upstream.repo}/commit/${c.sha}) ${c.subject}`);
    }

    lines.push('');
  }

  if (gated.length > 0) {
    lines.push(`### Gated (${gated.length})`, '');
    lines.push('Held back by a standing rule. Each still needs a disposition, but not a blind pick.', '');
    lines.push('| Commit | Subject | Gate | Why |', '| --- | --- | --- | --- |');

    for (const c of gated) {
      lines.push(
        `| [\`${c.sha.slice(0, 9)}\`](https://github.com/${upstream.repo}/commit/${c.sha}) | ${c.subject} | \`${c.gate}\` | ${c.reason} |`
      );
    }

    lines.push('');
  }

  return lines.join('\n');
}

// Our en.json is sorted case-insensitively; upstream's is not. Taking an
// upstream hunk wholesale is what breaks it, so guard the invariant here.
function checkEnJson() {
  const keys = Object.keys(JSON.parse(readFileSync(EN_JSON, 'utf8')));
  const bad = [];

  for (let i = 1; i < keys.length; i++) {
    if (keys[i - 1].toLowerCase() > keys[i].toLowerCase()) {
      bad.push(`${keys[i - 1]} before ${keys[i]}`);
    }
  }

  return bad;
}

function checkDispositions(state) {
  const valid = new Set(['pick', 'adapt', 'skip', 'have']);
  const problems = [];

  for (const [name, settled] of Object.entries(state.dispositions)) {
    for (const [sha, d] of Object.entries(settled)) {
      const at = `${name}/${sha.slice(0, 9)}`;

      if (!valid.has(d.disposition)) {
        problems.push(`${at}: unknown disposition "${d.disposition}"`);
      }

      if (!d.reason || d.reason.trim().length < 10) {
        problems.push(`${at}: needs a real reason`);
      }

      if (!d.subject) {
        problems.push(`${at}: missing subject`);
      }
    }
  }

  return problems;
}

const args = process.argv.slice(2);
const mode = args.find((a) => a.startsWith('--')) ?? '--report';
const state = JSON.parse(readFileSync(STATE, 'utf8'));

if (mode === '--check') {
  for (const p of checkDispositions(state)) {
    fail(p);
  }

  const enBad = checkEnJson();
  if (enBad.length > 0) {
    // One pre-existing violation is tracked separately; anything more is new.
    if (enBad.length > 1) {
      fail(`en.json is not sorted case-insensitively:\n  ${enBad.join('\n  ')}`);
    } else {
      console.warn(`warning: known en.json ordering issue: ${enBad[0]}`);
    }
  }

  let current = '';
  try {
    current = readFileSync(REPORT, 'utf8');
  } catch {
    fail('UPSTREAM_SYNC.md is missing — run with --report');
  }

  if (current) {
    const heads = parseHeads(current);

    if (!heads) {
      fail('UPSTREAM_SYNC.md has no upstream-heads pin — run with --report');
    } else if (current !== (await render(state, heads))) {
      fail('UPSTREAM_SYNC.md is stale — run with --report and commit the result');
    }
  }

  if (process.exitCode) {
    console.error('\nupstream-sync --check failed');
  } else {
    console.log('upstream-sync --check passed');
  }
} else if (mode === '--issue') {
  const name = args[args.indexOf('--upstream') + 1];
  const upstream = state.upstreams[name];

  if (!upstream) {
    fail(`unknown upstream "${name}" — expected one of ${Object.keys(state.upstreams).join(', ')}`);
    process.exit(1);
  }

  const commits = await backlog(name, upstream, state.dispositions);
  console.log(renderIssue(name, upstream, commits));
} else if (mode === '--attempt') {
  const name = args[args.indexOf('--upstream') + 1];
  const upstream = state.upstreams[name];

  if (!upstream) {
    fail(`unknown upstream "${name}" — expected one of ${Object.keys(state.upstreams).join(', ')}`);
    process.exit(1);
  }

  const result = await attempt(name, upstream, state);

  writeFileSync(join(ROOT, 'pr-body.md'), renderAttempt(result));
  writeFileSync(
    join(ROOT, 'issue-body.md'),
    renderIssue(name, upstream, result.commits, renderLeftovers(result))
  );

  // The workflow branches on these; keep it to one line of JSON on stdout so
  // the shell side stays a one-liner and cannot misread prose.
  console.log(
    JSON.stringify({
      upstream: name,
      branch: result.branch,
      outstanding: result.commits.length,
      applied: result.applied.length,
      conflicted: result.conflicted.length,
      gated: result.gated.length,
    })
  );
} else {
  const heads = Object.fromEntries(
    await Promise.all(
      Object.entries(state.upstreams).map(async ([n, u]) => [n, await branchHead(u)])
    )
  );

  writeFileSync(REPORT, await render(state, heads));
  console.log(`wrote ${REPORT}`);
}
