// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'audio': string;
  'audioLanguages': string;
  'blurred': string;
  'customFormatScore': string;
  'languages': string;
  'monitored': string;
  'path': string;
  'performers': string;
  'releaseDate': string;
  'releaseGroup': string;
  'runtime': string;
  'size': string;
  'status': string;
  'subtitles': string;
  'title': string;
  'video': string;
  'videoDynamicRangeType': string;
}
export const cssExports: CssExports;
export default cssExports;
