<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup>
    <!-- Suppress CA1825 for this project -->
    <NoWarn>$(NoWarn);CA1825</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="ImpromptuInterface" Version="8.0.6" />
    <PackageReference Include="NLog" Version="6.1.1" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentMigrator.Runner.Core" Version="8.0.1" />
    <PackageReference Include="FluentMigrator.Runner.Postgres" Version="8.0.1" />
  <PackageReference Include="FluentMigrator.Runner.SQLite" Version="8.0.1" />
  <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="10.0.3" />
  <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
  <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.3" />
  <PackageReference Include="Npgsql" Version="10.0.1" />
  <PackageReference Include="Sentry" Version="6.1.0" />
  <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.3" />
    <ProjectReference Include="..\NzbDrone.Core\Whisparr.Core.csproj" />
    <ProjectReference Include="..\NzbDrone.SignalR\Whisparr.SignalR.csproj" />
  </ItemGroup>
</Project>
